extends: 'airbnb'
parser:
  babel-eslint
rules:
  max-len:
    - error
    - 150
  'no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
  'arrow-body-style': off
  'no-shadow': off
  'react/jsx-filename-extension': off
  'react/forbid-prop-types': off
  'react/prop-types': off
  'jsx-a11y/label-has-for': off
globals:
  FB: true
  tableau: true
  window: true
