env:
  browser: true
extends: 'airbnb'
parser:
  babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - jsx-a11y
rules:
  max-len:
    - error
    - 150
  'no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
  'react/jsx-filename-extension': off
  'react/forbid-prop-types': off
  'react/prop-types': off
  'jsx-a11y/label-has-for': off
globals:
  FB: true
  tableau: true
